Feature/Link feature to documents
bluewave-labs/bluewave-dataroom pull request #100
Opened 2024-11-12 18:41 UTC by SepidehShahbazi

Issue #95 completed. 

Implemented: 

-  Adding Link column
-  Implementing link feature if there is an active link
-  Showing a grayed out version of the link icon if no link are available
-  Copy paste functionality to clip board on icon click

<img width="97" alt="Document_link_3" src="https://github.com/user-attachments/assets/d09228ba-4525-49e1-8a34-4677c9484336">

<img width="739" alt="DocumentPage" src="https://github.com/user-attachments/assets/f3e30c65-8151-47ab-a640-45b3fd8e174a">

2024-11-13 07:48 UTC, mahid797 commented on Client/src/app/documents/components/DocumentsTableRow.tsx
> +			<Toast
Good Use of Toast!

2024-11-13 08:32 UTC, mahid797 requested changes
Good Work  :+1:

2024-11-13 08:32 UTC, mahid797 commented on Client/src/app/documents/components/DocumentsTableRow.tsx
> +					setIsLinkCopied(!isLinkCopied);
Since copying text is a simple action (unlikely to throw an error), an error toast might not be necessary. However, a success toast would provide good user feedback. Your idea of using `CheckIcon` to indicate a successful copy is also good, but it should automatically revert to the original `LinkIcon` after a few seconds.

2024-11-13 08:32 UTC, mahid797 commented on Client/src/app/documents/components/DocumentsTableRow.tsx
> +					setIsLinkCopied(!isLinkCopied);
`setIsLinkCopied(!isLinkCopied)` toggles the state, which could cause issues. It would be better to explicitly set it to `true`.

2024-11-13 08:32 UTC, mahid797 commented on Client/src/app/documents/components/DocumentsTableRow.tsx
> +		document.createdLinks?.map((link) => {
The `handleLinkCopy` function currently uses the `map()` method, which is meant for returning a new array. Since we're not using the result, it would be more appropriate to use `forEach()` or directly accessing the specific link you want to copy (which link to copy would require further clarification so for now copy the first link).

`const linkToCopy = document.createdLinks?.[0]?.createdLink;`

2024-11-18 16:24 UTC, Paxxack commented on Client/src/app/documents/components/DocumentsTableRow.tsx
> +					setIsLinkCopied(!isLinkCopied);
Like Github is saying it is now outated and the situation already is changed for another version so just ignore this please. I wrote about this issue in the discord since I believe this is something important to know.

2024-11-18 18:27 UTC, merged