Refactor/#40-sepidehs-section
bluewave-labs/bluewave-dataroom pull request #45
Opened 2024-10-15 02:24 UTC by SepidehShahbazi

- Refactored DeleteConfirmationModal.
- Refactored UploadModal.
- Added both Modals to related pages.

2024-10-16 17:34 UTC, Paxxack requested changes
There’s just one small adjustment needed. For the use of the same component for drag and drop, please consult Mahid for his thoughts on this. He can decide if that change is necessary.

2024-10-16 17:34 UTC, Paxxack commented on Client/src/Components/UploadModal.tsx
I believe that this component and the DragAndDropBox in Client/src/app/documents/components/DragAndDropBox.tsx could potentially be consolidated into a single component.

2024-10-19 08:40 UTC, mahid797 commented on Client/src/Components/UploadModal.tsx
Both have different purposes and implementations. Would not improve code quality or performance

2024-10-20 17:11 UTC, Paxxack approved these changes

2024-10-21 15:50 UTC, mahid797 approved these changes

2024-10-21 15:50 UTC, merged