bug/Settings and Invite modal fixes
bluewave-labs/bluewave-dataroom pull request #80
Opened 2024-10-29 23:05 UTC by SepidehShahbazi

Issues #72 and #77 are completed: 

Settings page: 

- A few changes based on updated GlobalTheme.
- Adding Grid to the fields for fixing this problem: "Aligning the color code boxes on the left with the logo above ."

Invite new team member modal:

- Eliminating the default behavior of the fields.
- Adding the Dropdown component instead of textField and roles in the role selector input.
- Some changes on the Dropdown component.

<img width="442" alt="Settings_fix" src="https://github.com/user-attachments/assets/86d57b0b-429f-4317-b302-3eca242ed026">

<img width="254" alt="Invite" src="https://github.com/user-attachments/assets/850c5f05-f9a4-41bb-85a9-f47e483fa947">

2024-10-30 19:47 UTC, mahid797 requested changes
Just a few minor changes needed, but otherwise, excellent work!

2024-10-30 20:33 UTC, mahid797 commented on Client/src/components/ModalWrapper.tsx
> +						{ value: 'Select role', label: 'Select role' },
@SepidehShahbazi Also, please test if this or any recent changes to `ModelWrapper.tsx` have affected its implementation in other files.

2024-11-01 20:21 UTC, mahid797 approved these changes
The dropdown placeholder issue is more complicated than I anticipated, so will need to be resolved in another issue. #

2024-11-04 03:02 UTC, Paxxack approved these changes

2024-11-04 03:02 UTC, merged