bug/Documents, Profile and Pagination fixes
bluewave-labs/bluewave-dataroom pull request #82
Opened 2024-10-30 19:42 UTC by SepidehShahbazi

Issues #69, #73 and #75 are completed:

Documents page:

- Removing "Upload new document" button.
- The whole rectangular section for "Drag and Drop Box" is clickable.
- All the icons in the document list are center.
- fixing padding and height styles for the box of the drag and drop component.

Profile Page:

- the layout is like Figma now.

Pagination component:

- Exporting icons from Figma.
- Adding them as SVG files.
- Converting the SVG files to React Components called ArrowForwardIcon.tsx and ArrowBackIcon.tsx with "1px" stroke by default.
- Updating the Paginator.tsx.

Figma: 
<img width="103" alt="FigmaArrowBackIcon" src="https://github.com/user-attachments/assets/e75421dd-ceb5-4942-9ea3-c00e0e8e3446">

Designed: 
<img width="116" alt="DesignedArrowBackIcon" src="https://github.com/user-attachments/assets/8d46a6a1-522c-48bf-a25b-101f046d0cb2">

<img width="751" alt="Documents" src="https://github.com/user-attachments/assets/0e8e9173-cbdf-48b9-a8ab-01c56d1e4515">

<img width="805" alt="Profile" src="https://github.com/user-attachments/assets/6b64f6ea-0cd7-464e-88f7-a60f51905d9a">

2024-10-30 20:20 UTC, mahid797 requested changes
Looks Good mostly  :+1:

2024-10-30 20:20 UTC, mahid797 commented on Client/src/app/profile/page.tsx
> +				paddingRight: '23rem',
This is a simpler fix. Just remove the Box and use MUI Container i.e. 

```
<Container>
     <ProfileClient />
</Container>
```

2024-10-30 20:20 UTC, mahid797 commented on Client/src/app/documents/page.tsx
> +						<DragAndDropBox text="Drag and drop your document here or click to upload" />
You've removed the `height` prop from `DragAndDropBox` here, but not in the other instance. For consistency, could you align this with Figma’s requirements? Either remove the `height` prop entirely or set a default value based on Figma (preferably in `rem` or `vh` for responsiveness). I missed this detail when originally setting up the component.

2024-10-30 21:16 UTC, gorkem-bwl commented
Looks good to me!

2024-11-01 03:32 UTC, gorkem-bwl commented
Thanks. The design looks good!

2024-11-01 20:10 UTC, mahid797 approved these changes

2024-11-04 03:09 UTC, Paxxack approved these changes

2024-11-04 03:09 UTC, merged