bug/Sidebar fix
bluewave-labs/bluewave-dataroom pull request #85
Opened 2024-11-04 18:43 UTC by SepidehShahbazi

Issue #76 is completed:

Sidebar Component:

- Exporting contact icon from Figma.
- Adding it as SVG file.
- Converting the SVG files to React Components called ContactsIcon.tsx, DocumentsIcon.tsx and SettingsIcon.tsx.
- Updating the Sidebar.tsx.

<img width="95" alt="Sidebar" src="https://github.com/user-attachments/assets/b08910f5-fda4-46af-9b1e-bcc743ba6a03">

2024-11-05 00:11 UTC, mahid797 requested changes
Please make all of these component icons reusable so props can be passed to them. You can check my implementation of React Icons in `BluewaveLogo.tsx` or the icons in `public/assets/icons/auth/` as examples.

2024-11-05 00:11 UTC, mahid797 commented on Client/public/assets/icons/sidebar/ContactsIcon.tsx
> +const ContactsIcon = () => {
Please make all of these component Icons reusable

2024-11-05 00:11 UTC, mahid797 commented on Client/public/assets/icons/sidebar/DocumentsIcon.tsx
> +const DocumentsIcon = () => {
Same as above

2024-11-05 00:11 UTC, mahid797 commented on Client/public/assets/icons/sidebar/SettingsIcon.tsx
> +const SettingsIcon = () => {
Same as above

2024-11-05 08:03 UTC, mahid797 approved these changes

2024-11-11 21:01 UTC, Paxxack approved these changes
Good job!

2024-11-11 21:01 UTC, merged