Fix issues from #92 and #93
bluewave-labs/bluewave-dataroom pull request #99
Opened 2024-11-12 18:06 UTC by SajanGhuman

This PR resolves all the issues from issue #93 (Improve User Authentication Flow) and issue #93 (Authentication back-end fixes).

Enhance Forgot Password Workflow
   - Implement tokenization for secure password reset
   - Send a Reset Password email that directs users to the reset-password page

Email Verification
   - Send a verification email to users upon signup.
   - Prevent users from signing in until email verification is completed.

Automatic Login after Password Reset
   - Automatically log in users after they successfully reset their password.
   - Route users to the "Documents" page upon clicking the confirmation button on the password-reset-confirm page, instead of   redirecting them to the sign-in page.

Fix Sign-In and Log-Out Flickering Issue
    - Resolve the flickering that occurs on the Sign-In and Log-Out pages.

Remove Placeholder Authentication UI
    - Delete any placeholder Auth UI pages and folders to clean up the codebase.

Update User Schema
     - Add fields for First Name and Last Name.
     - Set default User role to "Admin".

2024-11-12 18:09 UTC, SajanGhuman commented
There is a small bug with "Automatic Login after Password Reset". Will be fixed soon.

2024-11-13 10:38 UTC, mahid797 requested changes
Great job👍🏼

2024-11-13 10:38 UTC, mahid797 commented on Client/prisma/schema.prisma
> +  role               UserRole             @default(ADMIN)
We should add a `updated_at` field here, good for records but also help in debugging. Also add for `@db.Timestamptz` for all times

2024-11-13 10:38 UTC, mahid797 commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
We need to temporarily disable the `ResetPasswordEmail` functionality since we currently lack the resources to send emails. The account verification emails should still be sent as they are, so no changes are required there. 

Returning the `resetPasswordUrl` as part of the response should suffice.

2024-11-13 10:38 UTC, mahid797 commented on Client/src/app/auth/forgot-password/page.tsx
>  				router.push(`/auth/reset-password?email=${encodeURIComponent(formData.email)}`);
Route to `resetPasswordUrl`

2024-11-13 10:38 UTC, mahid797 commented on Client/src/app/auth/reset-password/[token]/page.tsx
> +			const signInResult = await signIn('credentials', {
Shouldn't the signin be from `password-reset-confirm` page?

2024-11-13 10:38 UTC, mahid797 commented on Client/src/components/welcome_email.tsx
Please move all email templates to the `auth/components` directory for better organization. Also, maybe the filenames should be in `PascalCase` to maintain consistency with our naming conventions, unless there is a reason not to?

2024-11-13 10:38 UTC, mahid797 commented on Client/src/app/auth/sign-up/page.tsx
> +			router.push('/auth/check-email');
Since we’re currently unable to send emails, consider force-routing users directly to the intended page. 
The `check_email` page can have a temporary message: **_Please request your account admin to verify your email_**

2024-11-13 12:24 UTC, SajanGhuman commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
The email functionality is indeed working. It only works for one email as it is in testing.

2024-11-13 12:31 UTC, SajanGhuman commented on Client/src/components/welcome_email.tsx
Changed made with PascalCase naming convention.

2024-11-13 12:51 UTC, SajanGhuman commented on Client/prisma/schema.prisma
> +  role               UserRole             @default(ADMIN)
Changed Made

2024-11-13 13:49 UTC, mahid797 commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
I know its working but the issue is that even though the email is technically being sent, it’s not actually reaching anyone because we can’t fully utilize Resend on the free tier, plus we don’t have a proper domain set up. Until that changes, we need to disable the email functionality so that all developers can access and test the site without getting blocked by the reset-email step.

2024-11-13 13:51 UTC, mahid797 commented on Client/src/app/auth/sign-up/page.tsx
> +			router.push('/auth/check-email');
https://github.com/bluewave-labs/bluewave-dataroom/pull/99#discussion_r1840315919

> I know its working but the issue is that even though the email is technically being sent, it’s not actually reaching anyone because we can’t fully utilize Resend on the free tier, plus we don’t have a proper domain set up. Until that changes, we need to disable the email functionality so that all developers can access and test the site without getting blocked by the reset-email step.



Refer to comment above at to why I requested the change

2024-11-13 13:56 UTC, gorkem-bwl commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
> I know its working but the issue is that even though the email is technically being sent, it’s not actually reaching anyone because we can’t fully utilize Resend on the free tier, plus we don’t have a proper domain set up. Until that changes, we need to disable the email functionality so that all developers can access and test the site without getting blocked by the reset-email step.

Do you think creating a Gmail account works in this case for testing purposes? This is what we do in other projects.

2024-11-13 14:37 UTC, SajanGhuman commented
> There is a small bug with "Automatic Login after Password Reset". Will be fixed soon.

This is fixed now. When the user reset their password, They can auto sign in with a button click.

2024-11-13 14:43 UTC, mahid797 commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
I might be wrong but afaik, on free tier with no domain, Resend only allows you to send emails to one email address, which right now is set to your personal email (sajanghuman18@gmail.com). If I signup, it will throw an error, saying can only send to your email.

2024-11-13 14:44 UTC, mahid797 commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
> I might be wrong but afaik, on free tier with no domain, Resend only allows you to send emails to one email address, which right now is set to your personal email ([sajanghuman18@gmail.com](mailto:sajanghuman18@gmail.com)). If I signup, it will throw an error, saying can only send to your email.

Get Below error:

```
 POST /api/auth/register 500 in 2108ms
Email sending failed: {
  statusCode: 403,
  message: 'You can only send testing emails to your own email address (sajanghuman18@gmail.com). 
  To send emails to other recipients, please verify a domain at resend.com/domains, and change the `from` 
  address to an email using this domain.',
  name: 'validation_error'
}
```

2024-11-13 14:53 UTC, SajanGhuman commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
I am pretty sure I can add team members. Can you dm me your email, I will try to add it to resend. Also if that is not the case, you can just create your own account and swap the API keys if it works for you.

2024-11-13 14:56 UTC, mahid797 commented on Client/src/app/api/auth/resetPass/route.ts
> +	const { data, error } = await resend.emails.send({
> >

I will dm you on discord.

2024-12-07 15:14 UTC, mahid797 reviewed
Check Comment

2024-12-09 11:16 UTC, mahid797 approved these changes

2024-12-09 11:23 UTC, merged